Add -x|--service-name-prefix option

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -4,6 +4,7 @@
 VERSION="3.7.1"
 CLUSTER=false
 SERVICE=false
+SERVICE_PREFIX=false
 TASK_DEFINITION=false
 MAX_DEFINITIONS=0
 AWS_ASSUME_ROLE=false
@@ -30,6 +31,7 @@ https://github.com/silinternational/ecs-deploy
 
 One of the following is required:
     -n | --service-name          Name of service to deploy
+    -x | --service-name-prefix   Name prefix of service to deploy
     -d | --task-definition       Name of task definition to deploy
 
 Required arguments:
@@ -55,7 +57,7 @@ Optional arguments:
     --max-definitions            Number of Task Definition Revisions to persist before deregistering oldest revisions.
     --enable-rollback            Rollback task definition if new version is not running before TIMEOUT
     --force-new-deployment       Force a new deployment of the service. Default is false.
-    --use-latest-task-def   Will use the most recently created task definition as it's base, rather than the last used.
+    --use-latest-task-def        Will use the most recently created task definition as it's base, rather than the last used.
     --skip-deployments-check     Skip deployments check for services that take too long to drain old tasks
     --run-task                   Run created task now. If you set this, service-name are not needed.
     -v | --verbose               Verbose output
@@ -141,15 +143,23 @@ function assertRequiredArgumentsSet() {
               AWS_ECS="$AWS_ECS --profile $AWS_PROFILE"
     fi
 
-    if [ $SERVICE == false ] && [ $TASK_DEFINITION == false ]; then
-        echo "One of SERVICE or TASK DEFINITION is required. You can pass the value using -n / --service-name for a service, or -d / --task-definition for a task"
+    if [ $SERVICE == false ] && [ $SERVICE_PREFIX == false ] && [ $TASK_DEFINITION == false ]; then
+        echo "One of SERVICE, SERVICE_PREFIX or TASK DEFINITION is required. You can pass the value using -n / --service-name for a service, -x / --service-name-prefix for a service name prefix, or -d / --task-definition for a task"
         exit 5
+    fi
+    if [ $SERVICE != false ] && [ $SERVICE_PREFIX != false ]; then
+        echo "Only one of SERVICE or SERVICE PREFIX may be specified, but you supplied both"
+        exit 6
+    fi
+    if [ $SERVICE_PREFIX != false ] && [ $TASK_DEFINITION != false ]; then
+        echo "Only one of SERVICE PREFIX or TASK DEFINITION may be specified, but you supplied both"
+        exit 6
     fi
     if [ $SERVICE != false ] && [ $TASK_DEFINITION != false ]; then
         echo "Only one of SERVICE or TASK DEFINITION may be specified, but you supplied both"
         exit 6
     fi
-    if [ $SERVICE != false ] && [ $CLUSTER == false ]; then
+    if [[ $SERVICE != false || $SERVICE_PREFIX != false ]] && [ $CLUSTER == false ]; then
         echo "CLUSTER is required. You can pass the value using -c or --cluster"
         exit 7
     fi
@@ -281,7 +291,12 @@ function parseImageName() {
 }
 
 function getCurrentTaskDefinition() {
-    if [ $SERVICE != false ]; then
+    if [[ $SERVICE_PREFIX != false || $SERVICE != false ]]; then
+      if [ $SERVICE_PREFIX != false ]; then
+        # Get service from service prefix
+        SERVICE=$($AWS_ECS list-services --cluster $CLUSTER --query 'serviceArns[?contains(@, `'${SERVICE_PREFIX}'`)]' | jq -r .[0])
+      fi
+
       # Get current task definition arn from service
       TASK_DEFINITION_ARN=`$AWS_ECS describe-services --services $SERVICE --cluster $CLUSTER | jq -r .services[0].taskDefinition`
       TASK_DEFINITION=`$AWS_ECS describe-task-definition --task-def $TASK_DEFINITION_ARN`
@@ -530,6 +545,10 @@ if [ "$BASH_SOURCE" == "$0" ]; then
                 ;;
             -n|--service-name)
                 SERVICE="$2"
+                shift # past argument
+                ;;
+            -x|--service-name-prefix)
+                SERVICE_PREFIX="$2"
                 shift # past argument
                 ;;
             -d|--task-definition)
